/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class InputDataGUI extends javax.swing.JFrame {

    /**
     * Creates new form InputDataGUI
     */
    public InputDataGUI() {
        initComponents();
    }

     double totalMasuk = 0; 
     double totalKeluar = 0;
     double totalSelisih = 0;
     double totalKeseluruhan = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtEdit = new javax.swing.JButton();
        BtHapus = new javax.swing.JButton();
        BtKeluar = new javax.swing.JButton();
        BtSimpan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbTotal = new javax.swing.JLabel();
        TfTanggal = new javax.swing.JTextField();
        TfMasuk = new javax.swing.JTextField();
        TfKeluar = new javax.swing.JTextField();
        BtClean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TfAlasan = new javax.swing.JTextField();
        BtTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDuit = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        BtCetak = new javax.swing.JButton();
        BtImpor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APK");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        BtEdit.setText("Edit");
        BtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditActionPerformed(evt);
            }
        });

        BtHapus.setText("Hapus");
        BtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHapusActionPerformed(evt);
            }
        });

        BtKeluar.setText("Keluar");
        BtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtKeluarActionPerformed(evt);
            }
        });

        BtSimpan.setText("Simpan");
        BtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(BtEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel1.setText("Isi Dengan Benar Yaaa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Tanggal");

        jLabel3.setText("Uang Masuk");

        jLabel4.setText("Uang Keluar");

        LbTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LbTotal.setText("Uang yang anda miliki:");

        TfTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfTanggalKeyTyped(evt);
            }
        });

        TfMasuk.setText("Rp. ");
        TfMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfMasukActionPerformed(evt);
            }
        });
        TfMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfMasukKeyTyped(evt);
            }
        });

        TfKeluar.setText("Rp. ");
        TfKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfKeluarKeyTyped(evt);
            }
        });

        BtClean.setText("Bersihkan");
        BtClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCleanActionPerformed(evt);
            }
        });

        jLabel6.setText("Alasan ");

        TfAlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfAlasanActionPerformed(evt);
            }
        });

        BtTambah.setText("Tambah");
        BtTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtClean)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbTotal)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TfMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(TfKeluar))
                                        .addComponent(TfAlasan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TfKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TfAlasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(LbTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtClean)
                    .addComponent(BtTambah))
                .addGap(26, 26, 26))
        );

        TbDuit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Uang Masuk", "Uang Keluar", "Selisih", "Alasan"
            }
        ));
        TbDuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbDuitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbDuit);

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));

        BtCetak.setText("Cetak");
        BtCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCetakActionPerformed(evt);
            }
        });

        BtImpor.setText("Impor");
        BtImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImporActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtImpor, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtImpor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtCetak, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtKeluarActionPerformed
        new Login().setVisible(true);
            dispose(); //ini adalah code buat Keluar
    }//GEN-LAST:event_BtKeluarActionPerformed

    private void BtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSimpanActionPerformed
        DefaultTableModel model = (DefaultTableModel) TbDuit.getModel();
        if (TbDuit.getSelectedRow()==-1) {
            if (TbDuit.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "Tidak Ada Data yang Di Pilih");
            }else{
                JOptionPane.showMessageDialog(null, "Silahkan Pilih Data");
            }
        }else{
            
            // mengambil nilai uang masuk, keluar, dan selisih
            double masukLama = Double.parseDouble(model.getValueAt(TbDuit.getSelectedRow(), 1).toString().replace("Rp. ", ""));
            double keluarLama = Double.parseDouble(model.getValueAt(TbDuit.getSelectedRow(), 2).toString().replace("Rp. ", ""));
            double selisihLama = Double.parseDouble(model.getValueAt(TbDuit.getSelectedRow(), 3).toString().replace("Rp. ", ""));
            
            // mengurangi keseluruhan nilai dengan nilai yang lama
            totalMasuk -= masukLama;
            totalKeluar -= keluarLama;
            totalSelisih -= selisihLama;
            
            String masukText = TfMasuk.getText().replace("Rp. ", ""); // Mengambil nilai tanpa "Rp. "
            String keluarText = TfKeluar.getText().replace("Rp. ", ""); // Mengambil nilai tanpa "Rp. "

            // Menghitung selisih antara TfMasuk dan TfKeluar
            double masuk = Double.parseDouble(masukText.isEmpty() ? "0" : masukText);
            double keluar = Double.parseDouble(keluarText.isEmpty() ? "0" : keluarText);
            double selisih = masuk - keluar;
            
            model.setValueAt(TfTanggal.getText(), TbDuit.getSelectedRow(), 0);
            model.setValueAt(TfMasuk.getText(), TbDuit.getSelectedRow(), 1);
            model.setValueAt(TfKeluar.getText(), TbDuit.getSelectedRow(), 2);
            model.setValueAt("Rp. " + String.valueOf(selisih), TbDuit.getSelectedRow(), 3);
            model.setValueAt(TfAlasan.getText(), TbDuit.getSelectedRow(), 4);
            
            // menambahkan keseluruhan nilai dengan yang baru
            totalMasuk += masuk;
            totalKeluar += keluar;
            totalSelisih += selisih;
            
            // Tampilkan saldo
            LbTotal.setText("Uang yang anda miliki : Rp. " + String.valueOf(totalSelisih));
            
            BtTambah.setEnabled(true);
            JOptionPane.showMessageDialog((null), "Data berhasil di ubah");
            TfTanggal.setText("");
            TfMasuk.setText("Rp. ");
            TfKeluar.setText("Rp. ");
            TfAlasan.setText(""); 
            TfTanggal.requestFocus();
           
        }
    }//GEN-LAST:event_BtSimpanActionPerformed

    private void TbDuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbDuitMouseClicked
        DefaultTableModel model = (DefaultTableModel) TbDuit.getModel();
    }//GEN-LAST:event_TbDuitMouseClicked
    
    private void TfTanggalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfTanggalKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Silahkan Isi Hanya Dengan Angka");
        }
    }//GEN-LAST:event_TfTanggalKeyTyped

    private void TfMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfMasukActionPerformed

    private void TfMasukKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfMasukKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Silahkan Isi Hanya Dengan Angka");
        }
    }//GEN-LAST:event_TfMasukKeyTyped

    private void TfKeluarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfKeluarKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Silahkan Isi Hanya Dengan Angka");
        }
    }//GEN-LAST:event_TfKeluarKeyTyped

    private void TfAlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfAlasanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfAlasanActionPerformed

    private void BtCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCleanActionPerformed
        TfTanggal.setText("");
        TfMasuk.setText("Rp. ");
        TfKeluar.setText("Rp. ");
        TfAlasan.setText("");
        TfTanggal.requestFocus();
    }//GEN-LAST:event_BtCleanActionPerformed

    private void BtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditActionPerformed
        DefaultTableModel model = (DefaultTableModel) TbDuit.getModel();
        if (TbDuit.getSelectedRow()==-1) {
            if (TbDuit.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null, "Tidak Ada Data yang Di Pilih");
            }else{
                JOptionPane.showMessageDialog(null,"Silahkan Pilih Data");
            }
        }else{
        TfTanggal.setText(model.getValueAt(TbDuit.getSelectedRow(), 0).toString());
        TfMasuk.setText(model.getValueAt(TbDuit.getSelectedRow(), 1).toString());
        TfKeluar.setText(model.getValueAt(TbDuit.getSelectedRow(), 2).toString());
        TfAlasan.setText(model.getValueAt(TbDuit.getSelectedRow(), 4).toString());
        BtTambah.setEnabled(false); //Supaya ketika ditekan tombol edit maka tombol tambah false dan harus pencet tombol simpan
        }
    }//GEN-LAST:event_BtEditActionPerformed

    private void BtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHapusActionPerformed
        DefaultTableModel model = (DefaultTableModel) TbDuit.getModel();
        if (TbDuit.getSelectedRow()==-1) {
            if (TbDuit.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null, "Tidak Ada Data yang Di Pilih");
            }else{
                JOptionPane.showMessageDialog(null,"Silahkan Pilih Data");
            }
        }else{
            int a=JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data Tersebut ?", "select", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            
             // mengambil nilai uang masuk, keluar, dan selisih
            double masukLama = Double.parseDouble(model.getValueAt(TbDuit.getSelectedRow(), 1).toString().replace("Rp. ", ""));
            double keluarLama = Double.parseDouble(model.getValueAt(TbDuit.getSelectedRow(), 2).toString().replace("Rp. ", ""));
            double selisihLama = Double.parseDouble(model.getValueAt(TbDuit.getSelectedRow(), 3).toString().replace("Rp. ", ""));
            
            // mengurangi keseluruhan nilai dengan nilai yang lama
            totalMasuk -= masukLama;
            totalKeluar -= keluarLama;
            totalSelisih -= selisihLama;
            
             model.removeRow(TbDuit.getSelectedRow());
             JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
              // Tampilkan saldo
            LbTotal.setText("Uang yang anda miliki : Rp. " + String.valueOf(totalSelisih));
        }    
       }
    }//GEN-LAST:event_BtHapusActionPerformed

    private void BtTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTambahActionPerformed
         if (TfTanggal.getText().trim().equals("") || TfAlasan.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Tolong Isi Data Yang Kosong  !!! \n Silahkan lengkapi");
    } else {
        String masukText = TfMasuk.getText().replace("Rp. ", ""); // Mengambil nilai tanpa "Rp. "
        String keluarText = TfKeluar.getText().replace("Rp. ", ""); // Mengambil nilai tanpa "Rp. "
        
        // Menghitung selisih antara TfMasuk dan TfKeluar
        double masuk = Double.parseDouble(masukText.isEmpty() ? "0" : masukText);
        double keluar = Double.parseDouble(keluarText.isEmpty() ? "0" : keluarText);
        double selisih = masuk - keluar;
        
        // Menambahkan data ke dalam tabel
        DefaultTableModel model = (DefaultTableModel) TbDuit.getModel();
        model.addRow(new Object[]{TfTanggal.getText(), "Rp. " + masuk, "Rp. " + keluar, "Rp. " + selisih, TfAlasan.getText()});
        JOptionPane.showMessageDialog(null, "Data anda berhasil di input");
        
        // Memperbarui total uang masuk dan keluar
        totalMasuk += masuk;
        totalKeluar += keluar;
        totalSelisih += selisih;
        
        // Tampilkan saldo
            LbTotal.setText("Uang yang anda miliki : Rp. " + String.valueOf(totalSelisih));
    }
        TfTanggal.setText("");
        TfMasuk.setText("Rp. ");
        TfKeluar.setText("Rp. ");
        TfAlasan.setText("");
    }//GEN-LAST:event_BtTambahActionPerformed

    private void BtCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCetakActionPerformed
         try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("DataUang.txt"));
            
            for(int i = 0; i < TbDuit.getRowCount(); i++) { //membaca rows table
                for(int j = 0; j <TbDuit.getColumnCount(); j++) { //membaca column table
                    bw.write(TbDuit.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            
           JOptionPane.showMessageDialog(null, "Data Berhasil di Cetak");
           bw.close();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtCetakActionPerformed

    private void BtImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImporActionPerformed
        try {
            BufferedReader br = new BufferedReader(new FileReader("ImportData.txt"));
            
            DefaultTableModel model = (DefaultTableModel) TbDuit.getModel();
            Object[] lines = br.lines().toArray();
            
            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
                JOptionPane.showMessageDialog(null, "Data Berhasil Import");
            }
           
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtImporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCetak;
    private javax.swing.JButton BtClean;
    private javax.swing.JButton BtEdit;
    private javax.swing.JButton BtHapus;
    private javax.swing.JButton BtImpor;
    private javax.swing.JButton BtKeluar;
    private javax.swing.JButton BtSimpan;
    private javax.swing.JButton BtTambah;
    private javax.swing.JLabel LbTotal;
    private javax.swing.JTable TbDuit;
    private javax.swing.JTextField TfAlasan;
    private javax.swing.JTextField TfKeluar;
    private javax.swing.JTextField TfMasuk;
    private javax.swing.JTextField TfTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
